### ISSUE TITLE
Unable to run the calibration process in Part D - Demo System ID, Step 9

### ISSUE THREAD

**Issue by alessandromorra** [duckietown/docs-opmanual_duckiebot#118]
### Context

*What step were you trying in the documentation?*
Part D - Demo System ID, Step 9

*What command line were you running?*
roslaunch calibration calibration.launch veh:=kleinesentlein path:=/home/amorra/duckietown_sysid/rosbag/

### Problem

*What happened?*

I get following:

roslaunch calibration calibration.launch veh:=kleinesentlein path:=/home/amorra/duckietown_sysid/rosbag/
... logging to /home/amorra/.ros/log/a2491442-d701-11e8-aead-f45c899a1bf7/roslaunch-amorra-MacBookPro-11552.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://amorra-MacBookPro.local:39897/

SUMMARY
========

CLEAR PARAMETERS
 * /kinematic_calibration/

PARAMETERS
 * /kinematic_calibration/path: /home/amorra/duck...
 * /kinematic_calibration/veh: kleinesentlein
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    kinematic_calibration (calibration/kinematic_calibration.py)

auto-starting new master
process[master]: started with pid [11574]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to a2491442-d701-11e8-aead-f45c899a1bf7
process[rosout-1]: started with pid [11587]
started core service [/rosout]
process[kinematic_calibration-2]: started with pid [11595]
Traceback (most recent call last):
  File "/home/amorra/duckietown/Software/catkin_ws/src/05-teleop/calibration/src/kinematic_calibration.py", line 14, in <module>
    from duckietown_utils.path_utils import get_ros_package_path
  File "/home/amorra/duckietown/Software/catkin_ws/devel/lib/python2.7/dist-packages/duckietown_utils/__init__.py", line 35, in <module>
    exec(__fh.read())
  File "<string>", line 38, in <module>
  File "/home/amorra/duckietown/Software/catkin_ws/src/00-infrastructure/duckietown/include/duckietown_utils/download.py", line 1, in <module>
    from contracts.utils import indent
ImportError: No module named contracts.utils
================================================================================REQUIRED process [kinematic_calibration-2] has died!
process has died [pid 11595, exit code 1, cmd /home/amorra/duckietown/Software/catkin_ws/src/05-teleop/calibration/src/kinematic_calibration.py __name:=kinematic_calibration __log:=/home/amorra/.ros/log/a2491442-d701-11e8-aead-f45c899a1bf7/kinematic_calibration-2.log].
log file: /home/amorra/.ros/log/a2491442-d701-11e8-aead-f45c899a1bf7/kinematic_calibration-2*.log
Initiating shutdown!
================================================================================
[kinematic_calibration-2] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done

*What did you expect to happen?*

it to work...

### System information

Duckietown version: 

- [X] DT18 
- [ ] DT17

Duckiebot version: 

- [X] DB18
- [ ] DB17
- [ ] other: ___

Computer OS: 

- [ ] Ubuntu 18.04, native installation
- [X] Ubuntu 16.04, native installation
- [ ] Ubuntu 18.04, native installation
- [ ] Ubuntu 16.04, virtual machine
- [ ] OS X
- [ ] other: ___
 
### Additional notes

*Add any other notes about the problem here.*

### Screenshots

![error_sys_id](https://user-images.githubusercontent.com/32458198/47389615-81fe1e80-d715-11e8-85a5-5ed864d30bb1.png)

*If necessary, add screenshots to help explain your problem.*
**Note: text is preferred.**

**Comment by alessandromorra** [comment]
a fix to the problem is to just comment out following lanes in following files in

` ~/duckietown/Software/catkin_ws/src/00-infrastructure/duckietown/include/duckietown_utils`

1. file: `download.py`

comment out 1st lane: `#from contracts.utils import indent`

2. file: `networking.py`

comment out 6th lane: `#from contracts.utils import indent`

**Comment by AleksandarPetrov** [comment]
@selcukercan You might want to take a look
