### ISSUE TITLE
Extrinsic calibration problem

### ISSUE THREAD

**Issue by lapandic** [duckietown/docs-opmanual_duckiebot#47]
### Context

I was trying step 10.4. I successfully did the intrinsic calibration, I was able to download the calibration file. When I tried to do in the same run the extrinsic calibration I got the following error and the calibration yaml file was not generated in the folder. I noticed that it shut down picamera for some reason, and in the next try I started it manually after finishing the intrinsic calibration. Also, every time I run `dts calibrate` command it starts from the beginning.

````
dzenan:~/docs/docs-opmanual_duckiebot$ dts calibrate zmaj
INFO:dts:duckietown-shell 3.0.6
INFO:dts:

    Problems with a step in the Duckiebot operation manual?
    
        Report here: https://github.com/duckietown/docs-opmanual_duckiebot/issues
    
    
    Other problems?  
    
        Report here: https://github.com/duckietown/duckietown-shell-commands/issues
        
        Tips:
        
        - NEVER install duckietown-shell using "sudo". Instead use:
            
            pip install --user -U duckietown-shell
            
          Note the switch "--user" to install in ~/.local
        
        - Delete ~/.dt-shell to reset the shell to "factory settings".
          This is useful if some update fails.
          
          (Note: you will have to re-configure)
          
        - Last resort is deleting ~/.local and re-install from scratch.


/usr/local/lib/python2.7/dist-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
INFO:dts:I will ignore DOCKER_HOST because the calibrate command knows what it's doing.
master18: Pulling from duckietown/rpi-duckiebot-calibration
Digest: sha256:23ab4eab2bde0b8656fb3ab8036b7f177c255972a2076b878f76825f25ef008d
Status: Image is up to date for duckietown/rpi-duckiebot-calibration:master18
master18: Pulling from duckietown/rpi-duckiebot-base
Digest: sha256:c0919c521c989235d083001106c0a006be1fdd018104c345ef85728936a4d681
Status: Image is up to date for duckietown/rpi-duckiebot-base:master18
access control disabled, clients can connect from any host
Setting ROS_IP to host IP, which is 192.168.1.201
Writing "192.168.1.217 zmaj zmaj.local" into /etc/hosts
Activating ROS with shell: /bin/bash
Set DUCKIETOWN_ROOT to: /home/software
Set PYTHONPATH to: /home/software/catkin_ws/src:/opt/ros/kinetic/lib/python2.7/dist-packages
Activating development environment...

Position the checkerboard pattern in front of the Duckiebot and press ENTER.

... logging to /root/.ros/log/15125678-c717-11e8-8f45-b827eb6affaa/roslaunch-dzenanThinkPad13-90.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://192.168.1.201:32797/

SUMMARY
========

PARAMETERS
 * /rosdistro: kinetic
 * /rosversion: 1.12.13
 * /zmaj/decoder_node/publish_freq: 10.0

NODES
  /zmaj/
    intrinsic_calibrator (camera_calibration/cameracalibrator.py)

ROS_MASTER_URI=http://zmaj.local:11311/

process[zmaj/intrinsic_calibrator-1]: started with pid [99]
Exception in thread Thread-6 (most likely raised during interpreter shutdown):
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_innerQObject::~QObject: Timers cannot be stopped from another thread
[zmaj/intrinsic_calibrator-1] process has finished cleanly
log file: /root/.ros/log/15125678-c717-11e8-8f45-b827eb6affaa/zmaj-intrinsic_calibrator-1*.log
all processes on machine have died, roslaunch will exit
shutting down processing monitor...
... shutting down processing monitor complete
done
ros-picam
********************
Place the Duckiebot on the calibration patterns and press ENTER.

Setting ROS_IP to host IP, which is 192.168.1.217
Activating ROS with shell: /bin/bash
Set DUCKIETOWN_ROOT to: /home/software
Set PYTHONPATH to: /home/software/catkin_ws/src:/opt/ros/kinetic/lib/python2.7/dist-packages
Activating development environment...
   
rosrun complete_image_pipeline calibrate_extrinsics|  has_logger.py:12   - info           | Taking a picture. Say cheese!
mmal: mmal_vc_port_enable: failed to enable port vc.null_sink:in:0(OPQV): ENOSPC
mmal: mmal_port_enable: failed to enable connected port (vc.null_sink:in:0(OPQV))0x1cb8290 (ENOSPC)
mmal: mmal_connection_enable: output port couldn't be enabled
       quickapp|script_utils.py:60   - wrap_script_entry_point_noexit| Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/decent_params/utils/script_utils.py", line 49, in wrap_script_entry_point_noexit
    ret = function(args)
  File "/usr/local/lib/python2.7/dist-packages/quickapp/quick_app_base.py", line 167, in main
    ret = self.go()
  File "/home/software/catkin_ws/src/10-lane-control/complete_image_pipeline/include/complete_image_pipeline/calibrate_extrinsics.py", line 45, in go
    bgr = dtu.bgr_from_raspistill(out)
  File "/home/software/catkin_ws/src/00-infrastructure/duckietown/include/duckietown_utils/jpg.py", line 106, in bgr_from_raspistill
    with picamera.PiCamera() as camera:
  File "/usr/local/lib/python2.7/dist-packages/picamera/camera.py", line 433, in __init__
    self._init_preview()
  File "/usr/local/lib/python2.7/dist-packages/picamera/camera.py", line 513, in _init_preview
    self, self._camera.outputs[self.CAMERA_PREVIEW_PORT])
  File "/usr/local/lib/python2.7/dist-packages/picamera/renderers.py", line 558, in __init__
    self.renderer.inputs[0].connect(source).enable()
  File "/usr/local/lib/python2.7/dist-packages/picamera/mmalobj.py", line 2212, in enable
    prefix="Failed to enable connection")
  File "/usr/local/lib/python2.7/dist-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
PiCameraMMALError: Failed to enable connection: Out of resources

     rospy.core|        core.py:454  - signal_shutdown| signal_shutdown [atexit]
********************
Place the Duckiebot in a lane and press ENTER.
````

**Comment by lapandic** [comment]
It seems so. I've just tried again and it worked. Still I had to repeat the intrinsic calibration.
