### ISSUE TITLE
dts calibrate returning error

### ISSUE THREAD

**Issue by eeedWard** [duckietown/docs-opmanual_duckiebot#71]
### Context
Using dts calibrate <my hostname> returns an error. Ros camera calibration window does not open.
Ros-picam container crashes before the calibration procedure ask you to place the bot in front of the camera and press enter.

If I restart the ros-picam container and continue with the procedure it returns error anyway.

### Command line
*What command line did you run?*

dts calibrate TheDuckEmpire
     
What is the value of the `DOCKER_HOST` variable?

TheDuckEmpire.local

#### Software diagnostics
*What other containers are running or stopped?*
local health
roscore
ros-picam
base
server1
portainer1
watch tower

Put here the output of: 

    $ docker -H YOURDUCKIEBOT.local ps -a -q

2d3ae634af1a
fc127c25f191
e336a32122d7
5aae3a2e99f0
77cc8b5a4e91
49377a6470b3
6f21de8b0b0f
3fd0688265b5
c63b375d1fbb
6e2b9736c75e
588e01c56b05
06ef0242fc0b
0434c7ba5357
e54e818a5e41
921853e909fb
d31549e4dd11
9e57ef187b6f
c03566a11303
b009f2bfddac
5e8f596853e1
bc9c20f93b69
6375c13e8e47
5926f493bc78

#### Hardware diagnostics

What does the `rpi-health` diagnostics say?
Healthy

### Error report

*Please report here the **complete** error message. You can find the container log in the Portainer interface.*  

error in terminal:
first one (white color): docker: Error response from daemon: error while creating mount source path '/data': mkdir /data: read-only file system.

Second one (Red):
 quickapp|script_utils.py:60   - wrap_script_entry_point_noexit| Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/decent_params/utils/script_utils.py", line 49, in wrap_script_entry_point_noexit
    ret = function(args)
  File "/usr/local/lib/python2.7/dist-packages/quickapp/quick_app_base.py", line 167, in main
    ret = self.go()
  File "/home/software/catkin_ws/src/10-lane-control/complete_image_pipeline/include/complete_image_pipeline/calibrate_extrinsics.py", line 59, in go
    camera_info = get_camera_info_for_robot(robot_name)
  File "/home/software/catkin_ws/src/05-teleop/pi_camera/include/pi_camera/camera_info.py", line 73, in get_camera_info_for_robot
    fn = get_camera_info_config_file(robot_name)
  File "/home/software/catkin_ws/src/05-teleop/pi_camera/include/pi_camera/camera_info.py", line 135, in get_camera_info_config_file
    raise NoCameraInfoAvailable(msg)
NoCameraInfoAvailable: Cannot find intrinsic file for robot 'TheDuckEmpire';
['/data/config/calibrations', '/home/software/catkin_ws/src/00-infrastructure/duckietown/config/baseline/calibration']

If I restart the ros-picam container (which automatically shuts down) before pressing enter when asking to place the bot in front of the calibration checkboard, this error shows up.

 quickapp|script_utils.py:60   - wrap_script_entry_point_noexit| Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/decent_params/utils/script_utils.py", line 49, in wrap_script_entry_point_noexit
    ret = function(args)
  File "/usr/local/lib/python2.7/dist-packages/quickapp/quick_app_base.py", line 167, in main
    ret = self.go()
  File "/home/software/catkin_ws/src/10-lane-control/complete_image_pipeline/include/complete_image_pipeline/calibrate_extrinsics.py", line 45, in go
    bgr = dtu.bgr_from_raspistill(out)
  File "/home/software/catkin_ws/src/00-infrastructure/duckietown/include/duckietown_utils/jpg.py", line 106, in bgr_from_raspistill
    with picamera.PiCamera() as camera:
  File "/usr/local/lib/python2.7/dist-packages/picamera/camera.py", line 433, in __init__
    self._init_preview()
  File "/usr/local/lib/python2.7/dist-packages/picamera/camera.py", line 513, in _init_preview
    self, self._camera.outputs[self.CAMERA_PREVIEW_PORT])
  File "/usr/local/lib/python2.7/dist-packages/picamera/renderers.py", line 558, in __init__
    self.renderer.inputs[0].connect(source).enable()
  File "/usr/local/lib/python2.7/dist-packages/picamera/mmalobj.py", line 2212, in enable
    prefix="Failed to enable connection")
  File "/usr/local/lib/python2.7/dist-packages/picamera/exc.py", line 184, in mmal_check
    raise PiCameraMMALError(status, prefix)
PiCameraMMALError: Failed to enable connection: Out of resources

     rospy.core|        core.py:454  - signal_shutdown| signal_shutdown [atexit]
********************

Thanks

**Comment by eeedWard** [comment]
@AndreaCensi I was told by a TA to tag you in this. Thanks

**Comment by eeedWard** [comment]
The problem seems related to my Laptop rather than then the bot. I will probably try to do a fresh installation of Ubuntu 18..
