### ISSUE TITLE
sd card initialization error

### ISSUE THREAD

**Issue by eeedWard** [duckietown/docs-opmanual_duckiebot#89]
### Context

*What step were you trying in the documentation?*
sd card initialization error
*What command line were you running?*
dts init_sd_card --hostname educk --wifi AndroidAPEdo:hell3,duckietown:quackquack,WOKO:surfthorld! --country CH --compress
### Problem
Error
*What happened?*

*What did you expect to happen?*

### System information

Duckietown version: 

- [x ] DT18 
- [ ] DT17

Duckiebot version: 

- [x ] DB18
- [ ] DB17
- [ ] other: ___

Computer OS: 

- [ ] Ubuntu 18.04, native installation
- [ x] Ubuntu 16.04, native installation
- [ ] Ubuntu 18.04, native installation
- [ ] Ubuntu 16.04, virtual machine
- [ ] OS X
- [ ] other: ___
 
### Additional notes

*Add any other notes about the problem here.*

### Screenshots

*If necessary, add screenshots to help explain your problem.*
**Note: text is preferred.**
ERROR: .IOError: [Errno 13] Permission denied: '/home/edoardo/.dt-shell/commands/init_sd_card/stacks/DT18_00_basic.yaml'
Traceback (most recent call last):
  File "/home/edoardo/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 71, in cli_main
    shell.onecmd(cmdline)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/edoardo/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 422, in <lambda>
    do_command_lam = lambda s, w: do_command(klass, s, w)
  File "/home/edoardo/.local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 46, in do_command
    cls.command(shell, args)
  File "/home/edoardo/.dt-shell/commands/init_sd_card/command.py", line 190, in command
    step2function[step_name](shell, parsed)
  File "/home/edoardo/.dt-shell/commands/init_sd_card/command.py", line 468, in step_setup
    configure_images(parsed, user_data, add_file_local, add_file)
  File "/home/edoardo/.dt-shell/commands/init_sd_card/command.py", line 531, in configure_images
    _run_cmd(['docker-compose', '-f', lpath, 'config', '--quiet'])
  File "/home/edoardo/.dt-shell/commands/init_sd_card/command.py", line 742, in _run_cmd
    subprocess.check_call(cmd)
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['docker-compose', '-f', '/home/edoardo/.dt-shell/commands/init_sd_card/stacks/DT18_00_basic.yaml', 'config', '--quiet']' returned non-zero exit status 1

**Comment by AndreaCensi** [comment]
Are the directory `/home/edoardo/.dt-shell/commands` and below owned by root?
If so it means you have been running the shell as root or with sudo.
Delete `~/.dt-shell` and try again.

**Comment by eeedWard** [comment]
Thanks. Deleting the .dt-shell file seems to have helped. However, when running the "dts tok set" command I now get this error:

Duckietown Shell commands version 1.0.4
Traceback (most recent call last):
  File "/home/edoardo/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 71, in cli_main
    shell.onecmd(cmdline)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/edoardo/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 422, in <lambda>
    do_command_lam = lambda s, w: do_command(klass, s, w)
  File "/home/edoardo/.local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 41, in do_command
    cls.commands[word].do_command(cls.commands[word], shell, ' '.join(parts[1:]))
  File "/home/edoardo/.local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 52, in do_command
    cls.command(shell, args)
  File "/home/edoardo/.dt-shell/commands/tok/set/command.py", line 33, in command
    shell.sprint('args: %s' % args.__repr__())
AttributeError: 'DTShell' object has no attribute 'sprint'

**Comment by AleksandarPetrov** [comment]
@AndreaCensi just added troubleshooting for that in the docs, please close this

**Comment by AleksandarPetrov** [comment]
@AndreaCensi, don't close yet. Only partially fixed.

With @eeedWard we gave all permissions to all users (`chmod 777`) and the error persists. His user is the owner of the files as well.

**Comment by AndreaCensi** [comment]
I mean, it says:

```
ERROR: .IOError: [Errno 13] Permission denied: '/home/edoardo/.dt-shell/commands/init_sd_card/stacks/DT18_00_basic.yaml'
```

**Comment by eeedWard** [comment]
I burned the SD card using a laptop from a friend, in the end.
If it can be helpful, the main difference is that it asked him to enter the sudo password after the command (which was sent without using sudo). While for me it did not ask for anything and then showed a permission denied error.

**Comment by matlock08** [comment]
In Case anyone facing this issue in my case running ubuntu 18.04 the problem is because permissions on apparmor, you need to run below command:



`sudo dpkg-reconfigure apparmor`

And add you directory in this case /home/edoardo/.dt-shell

apparmor on Ubuntu prevents the access to the daemon to the directory

Hope this helps
