### ISSUE TITLE
Error when trying to open gui_tools

### ISSUE THREAD

**Issue by alessandromorra** [duckietown/docs-opmanual_duckiebot#96]
### Context

*What step were you trying in the documentation?*

9.3 Viewing an Image Stream on Your Laptop

*What command line were you running?*

dts start_gui_tools kleinesentlein.local

or

dts start_gui_tools kleinesentlein

### Problem

*What happened?*

I am not able to run start_gui_tools with both commands from above...

`alessandro@tina-remote:~$ dts start_gui_tools kleinesentlein.local
INFO:dts:duckietown-shell 3.0.19

dts :  Problems with a command?
    :  
    :  Report here: https://github.com/duckietown/duckietown-shell-commands/issues
    :  
    :  Troubleshooting:
    :  
    :  - If some commands update fail, delete ~/.dt-shell/commands
    :  
    :  - To reset the shell to "factory settings", delete ~/.dt-shell
    :  
    :    (Note: you will have to re-configure.)
/home/alessandro/.local/lib/python2.7/site-packages/requests/__init__.py:83: RequestsDependencyWarning: Old version of cryptography ([1, 2, 3]) may cause slowdown.
  warnings.warn(warning, RequestsDependencyWarning)
Duckietown Shell commands version 1.0.5
ping: unknown host kleinesentlein.local.local
Unable to locate kleinesentlein.local.local!
access control disabled, clients can connect from any host
Traceback (most recent call last):
  File "/home/alessandro/.local/lib/python2.7/site-packages/dt_shell/__init__.py", line 72, in cli_main
    shell.onecmd(cmdline)
  File "/usr/lib/python2.7/cmd.py", line 221, in onecmd
    return func(arg)
  File "/home/alessandro/.local/lib/python2.7/site-packages/dt_shell/cli.py", line 405, in <lambda>
    do_command_lam = lambda s, w: do_command(klass, s, w)
  File "/home/alessandro/.local/lib/python2.7/site-packages/dt_shell/dt_command_abs.py", line 46, in do_command
    cls.command(shell, args)
  File "/home/alessandro/.dt-shell/commands/start_gui_tools/command.py", line 36, in command
    start_gui_tools(parsed_args.hostname)
  File "/home/alessandro/.dt-shell/commands/start_gui_tools/command.py", line 62, in start_gui_tools
    env_vars=env_vars)
  File "/home/alessandro/.local/lib/python2.7/site-packages/docker/models/containers.py", line 766, in run
    detach=detach, **kwargs)
  File "/home/alessandro/.local/lib/python2.7/site-packages/docker/models/containers.py", line 823, in create
    create_kwargs = _create_container_args(kwargs)
  File "/home/alessandro/.local/lib/python2.7/site-packages/docker/models/containers.py", line 1036, in _create_container_args
    raise create_unexpected_kwargs_error('run', kwargs)
TypeError: run() got an unexpected keyword argument 'env_vars'

`

*What did you expect to happen?*

The gui_tools to work... 

### System information

Duckietown version: 

- [X] DT18 
- [ ] DT17

Duckiebot version: 

- [X] DB18
- [ ] DB17
- [ ] other: ___

Computer OS: 

- [ ] Ubuntu 18.04, native installation
- [X] Ubuntu 16.04, native installation
- [ ] Ubuntu 18.04, native installation
- [ ] Ubuntu 16.04, virtual machine
- [ ] OS X
- [ ] other: ___
 
### Additional notes

*Add any other notes about the problem here.*

### Screenshots

*If necessary, add screenshots to help explain your problem.*

![error_gui_tools](https://user-images.githubusercontent.com/32458198/47139410-0edf4d00-d2bc-11e8-9abb-6f80cffecb00.jpeg)

**Note: text is preferred.**

**Comment by alessandromorra** [comment]
I am still stuck on the same issue. I reinstalled the whole shell and got now the following issue - any suggestions?

![gui_tools](https://user-images.githubusercontent.com/32458198/47159746-d0af5100-d2ee-11e8-8d69-6102d4a72f33.jpeg)

**Comment by raabuchanan** [comment]
Are you trying to visualize the image stream? try setting ROS_MASTER_URI and running rqt_image_view
